version = "0.2"
date = "21 September 2017"
package = "rstats"
title = "RServe integration"
content = [[A package with statistical functions using Rserve.]]
url = "https://github.com/pedro-andrade-inpe/rstats"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
license = "LGPL-3"
